 client_id=""
 azure_tenant="-4714-b824-"
 azure_oai_api_scope="-8db4-5a46d93a8fc0/.default" 
 AZURE_ENDPOINT="sycom/everydayai"
 base_url="https://api.s"
 azure_endpoint=".com/everydayai"
 AZURE_OPENAI_ENDPOINT="https://api"
 OPENAI_API_ENDPOINT="https://api."
 OPENAI_API_VERSION="2024-02-01"
 SUBSCRIPTION_KEY="0"
 PINECONE_API_KEY="d33a"
 INPUT_FOLDER="/Users/nkotha1/PycharmProjects/pythonProject/source_documents/" 
 CHROMA_STORE="/Users/nkotha1/PycharmProjects/pythonProject/chromastore"